name: Lyrics Site Rails Test
on: [pull_request]

jobs:
  rubocop-test:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: gem install rubocop rubocop-rspec rubocop-rails
      - name: Check code
        run: git diff-tree -r --no-commit-id --name-only $(git rev-parse --abbrev-ref HEAD)@\{u\} HEAD | xargs ls -1 2>/dev/null | grep '\.rb$' | xargs bundle exec rubocop --force-exclusion
env:
  RUBY_VERSION: 2.7.4
